### ISSUE TITLE
investigate using docker

### ISSUE THREAD

**Issue by danielalazzara** [danielalazzara/basket-api#8]
Investigate using docker to run `basket-api`

Reference:
- https://www.freecodecamp.org/news/what-is-docker-learn-how-to-use-containers-with-examples/
- https://www.freecodecamp.org/news/the-docker-handbook/
- https://www.freecodecamp.org/news/tag/docker-containers/

**Comment by markgreene74** [comment]
```
$ docker run python:3.7-slim python --version
Python 3.7.16
```

```
$ docker run python:3.11-slim python --version
Python 3.11.1
```

```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

```
$ docker image ls -a
REPOSITORY    TAG         IMAGE ID       CREATED         SIZE
python        3.7-slim    7ef53f615a8b   22 hours ago    123MB
python        3.11-slim   6c6673d57b08   26 hours ago    128MB
ubuntu        latest      6b7dfa7e8fdb   6 weeks ago     77.8MB
alpine        latest      49176f190c7e   2 months ago    7.05MB
hello-world   latest      feb5d9fea6a5   16 months ago   13.3kB
```

**Comment by markgreene74** [comment]
Some useful links for your reference @danielalazzara :
- [Dockerfile reference](https://docs.docker.com/engine/reference/builder/)
- [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

You can use `docker builder prune` [(docs)](https://docs.docker.com/engine/reference/commandline/builder_prune/) to remove the build cache, for example:
```
$ docker builder prune -a
WARNING! This will remove all build cache. Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
```

**Comment by markgreene74** [comment]
See https://fastapi.tiangolo.com/zh/deployment/manually/#run-the-server-program

So the `Dockerfile` should be changed like in this example:
```
$ cat Dockerfile 
...
CMD uvicorn main:app --host 0.0.0.0 --port 8000
```

After which we should rebuild:
```
$ docker build -t basket-api .
...
Successfully built e640f5932525
Successfully tagged basket-api:latest
```

And if we run the container like in this example:
```
$ docker run -d -p 8000:8000 --rm basket-api
2f2674e19a48aac825126477d4c0447e34fe80f010a9baa36999a632011de492
$
```

Then
```
$ curl http://127.0.0.1:8000
{"Version":"0.1"}
```
